INSERT INTO countries (id, name) VALUES
  (default ,'Afghanistan'),
  (default ,'Åland Islands'),
  (default ,'Albania'),
  (default ,'Algeria'),
  (default ,'American Samoa'),
  (default ,'Andorra'),
  (default ,'Angola'),
  (default ,'Anguilla'),
  (default ,'Antarctica'),
  (default ,'Antigua and Barbuda'),
  (default ,'Argentina'),
  (default ,'Armenia'),
  (default ,'Aruba'),
  (default ,'Australia'),
  (default ,'Austria'),
  (default ,'Azerbaijan'),
  (default ,'Bahamas'),
  (default ,'Bahrain'),
  (default ,'Bangladesh'),
  (default ,'Barbados'),
  (default ,'Belarus'),
  (default ,'Belgium'),
  (default ,'Belize'),
  (default ,'Benin'),
  (default ,'Bermuda'),
  (default ,'Bhutan'),
  (default ,'Bolivia, Plurinational State of'),
  (default ,'Bonaire, Sint Eustatius and Saba'),
  (default ,'Bosnia and Herzegovina'),
  (default ,'Botswana'),
  (default ,'Bouvet Island'),
  (default ,'Brazil'),
  (default ,'British Indian Ocean Territory'),
  (default ,'Brunei Darussalam'),
  (default ,'Bulgaria'),
  (default ,'Burkina Faso'),
  (default ,'Burundi'),
  (default ,'Cambodia'),
  (default ,'Cameroon'),
  (default ,'Canada'),
  (default ,'Cape Verde'),
  (default ,'Cayman Islands'),
  (default ,'Central African Republic'),
  (default ,'Chad'),
  (default ,'Chile'),
  (default ,'China'),
  (default ,'Christmas Island'),
  (default ,'Cocos (Keeling) Islands'),
  (default ,'Colombia'),
  (default ,'Comoros'),
  (default ,'Congo'),
  (default ,'Congo, the Democratic Republic of the'),
  (default ,'Cook Islands'),
  (default ,'Costa Rica'),
  (default ,'Côte d''Ivoire'),
  (default ,'Croatia'),
  (default ,'Cuba'),
  (default ,'Curaçao'),
  (default ,'Cyprus'),
  (default ,'Czech Republic'),
  (default ,'Denmark'),
  (default ,'Djibouti'),
  (default ,'Dominica'),
  (default ,'Dominican Republic'),
  (default ,'Ecuador'),
  (default ,'Egypt'),
  (default ,'El Salvador'),
  (default ,'Equatorial Guinea'),
  (default ,'Eritrea'),
  (default ,'Estonia'),
  (default ,'Ethiopia'),
  (default ,'Falkland Islands (Malvinas)'),
  (default ,'Faroe Islands'),
  (default ,'Fiji'),
  (default ,'Finland'),
  (default ,'France'),
  (default ,'French Guiana'),
  (default ,'French Polynesia'),
  (default ,'French Southern Territories'),
  (default ,'Gabon'),
  (default ,'Gambia'),
  (default ,'Georgia'),
  (default ,'Germany'),
  (default ,'Ghana'),
  (default ,'Gibraltar'),
  (default ,'Greece'),
  (default ,'Greenland'),
  (default ,'Grenada'),
  (default ,'Guadeloupe'),
  (default ,'Guam'),
  (default ,'Guatemala'),
  (default ,'Guernsey'),
  (default ,'Guinea'),
  (default ,'Guinea-Bissau'),
  (default ,'Guyana'),
  (default ,'Haiti'),
  (default ,'Heard Island and McDonald Islands'),
  (default ,'Holy See (Vatican City State)'),
  (default ,'Honduras'),
  (default ,'Hong Kong'),
  (default ,'Hungary'),
  (default ,'Iceland'),
  (default ,'India'),
  (default ,'Indonesia'),
  (default ,'Iran, Islamic Republic of'),
  (default ,'Iraq'),
  (default ,'Ireland'),
  (default ,'Isle of Man'),
  (default ,'Israel'),
  (default ,'Italy'),
  (default ,'Jamaica'),
  (default ,'Japan'),
  (default ,'Jersey'),
  (default ,'Jordan'),
  (default ,'Kazakhstan'),
  (default ,'Kenya'),
  (default ,'Kiribati'),
  (default ,'Korea, Democratic People''s Republic of'),
  (default ,'Korea, Republic of'),
  (default ,'Kuwait'),
  (default ,'Kyrgyzstan'),
  (default ,'Lao People''s Democratic Republic'),
  (default ,'Latvia'),
  (default ,'Lebanon'),
  (default ,'Lesotho'),
  (default ,'Liberia'),
  (default ,'Libya'),
  (default ,'Liechtenstein'),
  (default ,'Lithuania'),
  (default ,'Luxembourg'),
  (default ,'Macao'),
  (default ,'Macedonia, the former Yugoslav Republic of'),
  (default ,'Madagascar'),
  (default ,'Malawi'),
  (default ,'Malaysia'),
  (default ,'Maldives'),
  (default ,'Mali'),
  (default ,'Malta'),
  (default ,'Marshall Islands'),
  (default ,'Martinique'),
  (default ,'Mauritania'),
  (default ,'Mauritius'),
  (default ,'Mayotte'),
  (default ,'Mexico'),
  (default ,'Micronesia, Federated States of'),
  (default ,'Moldova, Republic of'),
  (default ,'Monaco'),
  (default ,'Mongolia'),
  (default ,'Montenegro'),
  (default ,'Montserrat'),
  (default ,'Morocco'),
  (default ,'Mozambique'),
  (default ,'Myanmar'),
  (default ,'Namibia'),
  (default ,'Nauru'),
  (default ,'Nepal'),
  (default ,'Netherlands'),
  (default ,'New Caledonia'),
  (default ,'New Zealand'),
  (default ,'Nicaragua'),
  (default ,'Niger'),
  (default ,'Nigeria'),
  (default ,'Niue'),
  (default ,'Norfolk Island'),
  (default ,'Northern Mariana Islands'),
  (default ,'Norway'),
  (default ,'Oman'),
  (default ,'Pakistan'),
  (default ,'Palau'),
  (default ,'Palestinian Territory, Occupied'),
  (default ,'Panama'),
  (default ,'Papua New Guinea'),
  (default ,'Paraguay'),
  (default ,'Peru'),
  (default ,'Philippines'),
  (default ,'Pitcairn'),
  (default ,'Poland'),
  (default ,'Portugal'),
  (default ,'Puerto Rico'),
  (default ,'Qatar'),
  (default ,'Réunion'),
  (default ,'Romania'),
  (default ,'Russian Federation'),
  (default ,'Rwanda'),
  (default ,'Saint Barthélemy'),
  (default ,'Saint Helena, Ascension and Tristan da Cunha'),
  (default ,'Saint Kitts and Nevis'),
  (default ,'Saint Lucia'),
  (default ,'Saint Martin (French part)'),
  (default ,'Saint Pierre and Miquelon'),
  (default ,'Saint Vincent and the Grenadines'),
  (default ,'Samoa'),
  (default ,'San Marino'),
  (default ,'Sao Tome and Principe'),
  (default ,'Saudi Arabia'),
  (default ,'Senegal'),
  (default ,'Serbia'),
  (default ,'Seychelles'),
  (default ,'Sierra Leone'),
  (default ,'Singapore'),
  (default ,'Sint Maarten (Dutch part)'),
  (default ,'Slovakia'),
  (default ,'Slovenia'),
  (default ,'Solomon Islands'),
  (default ,'Somalia'),
  (default ,'South Africa'),
  (default ,'South Georgia and the South Sandwich Islands'),
  (default ,'South Sudan'),
  (default ,'Spain'),
  (default ,'Sri Lanka'),
  (default ,'Sudan'),
  (default ,'Suriname'),
  (default ,'Svalbard and Jan Mayen'),
  (default ,'Swaziland'),
  (default ,'Sweden'),
  (default ,'Switzerland'),
  (default ,'Syrian Arab Republic'),
  (default ,'Taiwan, Province of China'),
  (default ,'Tajikistan'),
  (default ,'Tanzania, United Republic of'),
  (default ,'Thailand'),
  (default ,'Timor-Leste'),
  (default ,'Togo'),
  (default ,'Tokelau'),
  (default ,'Tonga'),
  (default ,'Trinidad and Tobago'),
  (default ,'Tunisia'),
  (default ,'Turkey'),
  (default ,'Turkmenistan'),
  (default ,'Turks and Caicos Islands'),
  (default ,'Tuvalu'),
  (default ,'Uganda'),
  (default ,'Ukraine'),
  (default ,'United Arab Emirates'),
  (default ,'United Kingdom'),
  (default ,'United States'),
  (default ,'United States Minor Outlying Islands'),
  (default ,'Uruguay'),
  (default ,'Uzbekistan'),
  (default ,'Vanuatu'),
  (default ,'Venezuela, Bolivarian Republic of'),
  (default ,'Viet Nam'),
  (default ,'Virgin Islands, British'),
  (default ,'Virgin Islands, U.S.'),
  (default ,'Wallis and Futuna'),
  (default ,'Western Sahara'),
  (default ,'Yemen'),
  (default ,'Zambia'),
  (default ,'Zimbabwe');

INSERT INTO universities (id, name, country_id) VALUES
  (default , 'Georgetown University', 2),
  (default , 'Boston University', 2),
  (default , 'American University', 2),
  (default , 'The George Washington University', 2),
  (default , 'University of Delhi', 1),
  (default , 'University of Zambia', 3);

INSERT INTO category (id, name, type) VALUES
  -- team
  (default , 'Leadership', 'team'),
  (default , 'Team', 'team'),
  (default , 'Mentors and Collaborators', 'team'),
  -- vizOfDay
  (default , 'Health Monday', 'vizOfDay'),
  (default , 'Tech Tuesday', 'vizOfDay'),
  (default , 'Economics Wednesday', 'vizOfDay'),
  (default , 'Repost Thursday', 'vizOfDay'),
  (default , 'Trending Friday', 'vizOfDay'),
  -- visual
  (default , 'Other', 'visual'),
  (default , 'Health', 'visual'),
  (default , 'Tech', 'visual'),
  (default , 'Economics', 'visual');

INSERT INTO 
  users
  (id, role, category_id, email, password, type, status, dob, firstname, lastname, avatar, gender, mobile, created_at)
VALUES
  ( default,
    null,
    1,
    'superadmin@techuz.com',
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    3,
    1, 
    '12/12/1993',   
    'Super',
    'Admin',
    'storage/default.jpeg',
    'Male',
    '9595959595',
    (now() + INTERVAL '1 SECOND')
  ),
  ( default,
    null,
    1,
    'niravgoswami@techuz.com',
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    2,
    1, 
    '12/12/1993',   
    'Nirav',
    'Goswami',
    'storage/default.jpeg',
    'Male',
    '9595959595',
    (now() + INTERVAL '2 SECOND')
  ),
  ( default,
    null,
    1,
    'testuser@techuz.com',    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    '12/12/1993',   
    'Techuz',
    'User',
    'storage/default.jpeg',
    'Male',
    '9595959595',
    (now() + INTERVAL '3 SECOND')
  ),
  -- Leader
  ( default,
    'Director of the Center for Global Data Visualization',
    1,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Rob',
    'Segan',
    'storage/team/Rob-Segan.jpg',
    'Male',
    null,
    (now() + INTERVAL '4 SECOND')
  ),
  ( default,
    'Senior Director of Global Programs and Innovation',
    1,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Darlene',
    'Irby',
    'storage/team/Darlene-Irby.jpg',
    'Male',
    null,
    (now() + INTERVAL '5 SECOND')
  ),
  ( default,
    'Content Manager, Center for Global Data Visualization',
    1,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Neelima',
    'Grover',
    'storage/team/Neelima-Grover.jpg',
    'Male',
    null,
    (now() + INTERVAL '6 SECOND')
  ),
  -- Team
  ( default,
    'Founder and Chairperson of the QED Group',
    2,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Keshav',
    'Sundar',
    'storage/team/Keshav-Sundar.jpg',
    'Male',
    null,
    (now() + INTERVAL '7 SECOND')
  ),
  ( default,
    'Information and Communication Technology (ICT) Advisor',
    2,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Matthew',
    'Deas',
    'storage/team/Matthew-Deas.jpg',
    'Male',
    null,
    (now() + INTERVAL '8 SECOND')
  ),
  ( default,
    'Senior Data Scientist',
    2,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Reema',
    'Rustagi',
    'storage/team/Reema-Rustagi.jpg',
    'Male',
    null,
    (now() + INTERVAL '9 SECOND')
  ),
  ( default,
    'Global Health Solutions and Data Visualization Intern',
    2,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Jiahao',
    'Xu',
    'storage/team/img4.jpg',
    'Male',
    null,
    (now() + INTERVAL '10 SECOND')
  ),
  ( default,
    'Junior Data Scientist',
    2,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Sonu',
    'Singh',
    'storage/team/Sonu-Singh.jpg',
    'Male',
    null,
    (now() + INTERVAL '11 SECOND')
  ),
  ( default,
    'Intern',
    2,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Prachi',
    'Jain',
    'storage/team/img4.jpg',
    'Male',
    null,
    (now() + INTERVAL '12 SECOND')
  ),
  ( default,
    'Intern',
    2,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Rashika',
    'Jakhmola',
    'storage/team/img4.jpg',
    'Male',
    null,
    (now() + INTERVAL '13 SECOND')
  ),
  -- Mentors and Collaborators
  ( default,
    'Asia Regional Director, QED Group',
    3,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Siddhi',
    'Arayal',
    'storage/team/Siddhi-Arayal.jpg',
    'Male',
    null,
    (now() + INTERVAL '14 SECOND')
  ),
  ( default,
    'Director of Monitoring, Evaluation and Learning (MEL), QED Group',
    3,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Micah',
    'Frumkin',
    'storage/team/Micah-Frumkin.jpg',
    'Male',
    null,
    (now() + INTERVAL '15 SECOND')
  ),
  ( default,
    'Senior Director of Business Development, QED Group',
    3,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'John',
    'Haederle',
    'storage/team/John-Haederle.jpg',
    'Male',
    null,
    (now() + INTERVAL '16 SECOND')
  ),
  ( default,
    'Executive Vice President, QED Group<',
    3,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Patrick',
    'Lohmeyer',
    'storage/team/Patrick-Lohmeyer.jpg',
    'Male',
    null,
    (now() + INTERVAL '17 SECOND')
  ),
  ( default,
    'Strategic Communications, High-Profile Event Production, Corporate Engagement and Diplomatic Protocol, Clay Doherty',
    3,
    null,    
    '$2a$08$juigt7gMjIom7Q5GMcGaPeDcV.0LmYoHb5f66ARrkr68m1y.1RPwG',
    1,
    1, 
    null,   
    'Clay',
    'Doherty',
    'storage/team/img4.jpg',
    'Male',
    null,
    (now() + INTERVAL '18 SECOND')
  );

INSERT INTO homepage_about (id, content) VALUES
  (default , 'The Center for Development Data Visualization (CDDV) works with the Tableau Foundation and 18
        leading universities across 6 continents to uncover hidden stories in data to maximize dollars to results
        in international development. Powered by QED and it’s 20 years of experience in international
        development and more than $3.5B programs monitored across 96 countries, CDDV has grown to
        become a leader in international development data analysis and visualization. To learn more about
        QED click <a target="_blank" href="https://www.qedgroupllc.com/approach/">here</a>.');  

INSERT INTO aboutpage_about (id, content) VALUES
  (default , 'Twelve years after the publication of Moneyball, the use of data analytics has become common place in the world of sports and business, but it is underutilized in the design and evaluation of international development programs. Our aim is to be a resource for those looking to gain a greater understanding of how to use data analytics to provide the greatest benefit of each dollar spent, to underserved populations most in need.');  

INSERT INTO cms_news (id, content) VALUES
  (default, '“Tableau Foundation joins CDDV in the development of a data visualization training”'),
  (default, '“CDDV welcomes Prachi Jain and Rashika Jahomla as its two newest Fellows”'),
  (default, '“Professor Ami Gates sits down with CDDV to discuss data science at Georgetown”');

INSERT INTO cms_journey (id, nav_title, header, content, avatar) VALUES
  (default, '2012', '2012', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s.', 'storage/journey/Journey-2012.jpg'),
  (default, '2013', '2013', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s.', 'storage/journey/Journey-2012.jpg'),
  (default, '2014', '2014', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s.', 'storage/journey/Journey-2012.jpg'),
  (default, '2015', '2015', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s.', 'storage/journey/Journey-2012.jpg'),
  (default, '2016', '2016', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s.', 'storage/journey/Journey-2012.jpg'),
  (default, '2017', '2017', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s.', 'storage/journey/Journey-2012.jpg'),
  (default, '2018', '2018', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s.', 'storage/journey/Journey-2012.jpg');

INSERT INTO cms_partners (id, avatar, title) VALUES
 (default, 'storage/logos/American-University.png', 'American-University'),
 (default, 'storage/logos/arizona-state-university.png', 'arizona-state-university'),
 (default, 'storage/logos/Boston-University.png', 'Boston-University'),
 (default, 'storage/logos/Dartmouth.jpg', 'Dartmouth'),
 (default, 'storage/logos/Dev-Results.png', 'Dev-Results'),
 (default, 'storage/logos/Fraym.png', 'Fraym'),
 (default, 'storage/logos/Georgetown.png', 'Georgetown'),
 (default, 'storage/logos/GW-University.png', 'GW-University'),
 (default, 'storage/logos/Hansraj-College.png', 'Hansraj-College'),
 (default, 'storage/logos/Marymount-University.jpg', 'Marymount-University'),
 (default, 'storage/logos/Premise.png', 'Premise'),
 (default, 'storage/logos/Tableau-Foundation.png', 'Tableau-Foundation'),
 (default, 'storage/logos/techuz.jpg', 'techuz'),
 (default, 'storage/logos/University-of-Arkansas.png', 'University-of-Arkansas'),
 (default, 'storage/logos/University-of-Calgary.jpg', 'University-of-Calgary'),
 (default, 'storage/logos/University-of-Houston.png', 'University-of-Houston'),
 (default, 'storage/logos/University-of-Zambia.png', 'University-of-Zambia');

